name: 🚦 CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  eslint:
    name: 🔬 ESLint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup
      - name: ESLint
        run: pnpm run lint:js
      - name: "notify vercel"
        uses: "vercel/repository-dispatch/actions/status@v1"
        with:
          name: "Vercel - slow-zone: 🔬 ESLint"

  stylelint:
    name: 🎨 Stylelint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup
      - name: Stylelint
        run: pnpm run lint:css
      - name: "notify vercel"
        uses: "vercel/repository-dispatch/actions/status@v1"
        with:
          name: "Vercel - slow-zone: 🎨 Stylelint"

  prettier:
    name: 💅 Prettier
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup
      - name: Prettier
        run: pnpm run prettier:check
      - name: "notify vercel"
        uses: "vercel/repository-dispatch/actions/status@v1"
        with:
          name: "Vercel - slow-zone: 💅 Prettier"

  typecheck:
    name: 👾 TypeScript
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup
      - name: TypeScript
        run: pnpm run typecheck
      - name: "notify vercel"
        uses: "vercel/repository-dispatch/actions/status@v1"
        with:
          name: "Vercel - slow-zone: 👾 TypeScript"
